display = "None" # Txt, Tui, None.
cache = true  # true if you want to use pomod-fetch 

[time]
hours = 0
minutes = 0
seconds = 10

[audio]
play = true # need music to wake you up?
path = "/home/charles/.config/pomod/notify1.mp3"
time = 3 # Music duration (in seconds)

[notify]
notify = true # need desktop notifications?
message = "it is time to take a break"
